;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        c-electric-brace
        c-electric-paren
        c-electric-semi&comma
        c-electric-star
        c-indent-line-or-region
        capitalize-dwim
        downcase-dwim
        electric-newline-and-maybe-indent
        electric-pair-delete-pair
        forward-sexp
        indent-for-tab-command
        mark-sexp
        meow-append
        meow-back-symbol
        meow-back-word
        meow-block
        meow-bounds-of-thing
        meow-change
        meow-delete
        meow-end-of-thing
        meow-find
        meow-inner-of-thing
        meow-insert
        meow-insert-exit
        meow-join
        meow-kill
        meow-left
        meow-mark-symbol
        meow-mark-word
        meow-next
        meow-next-symbol
        meow-next-word
        meow-prev
        meow-reverse
        meow-right
        meow-save
        meow-till
        meow-yank
        replace-regexp
        swb/meow-line
        upcase-dwim
        ))

(setq mc/cmds-to-run-once
      '(
        meow-undo
        swb/meow-find-mc
        swb/meow-till-mc
        swb/multiple-cursors-hydra/mc/edit-lines
        swb/multiple-cursors-hydra/mc/mark-next-like-this
        swb/multiple-cursors-hydra/mc/mark-previous-like-this
        swb/multiple-cursors-hydra/mc/skip-to-next-like-this
        swb/multiple-cursors-hydra/mc/skip-to-previous-like-this
        swb/multiple-cursors-hydra/mc/unmark-next-like-this
        swb/multiple-cursors-hydra/mc/unmark-previous-like-this
        swb/multiple-cursors-hydra/nil
        switch-to-buffer
        text-scale-adjust
        ))
