;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        c-electric-paren
        forward-sexp
        indent-for-tab-command
        mark-sexp
        meow-append
        meow-back-symbol
        meow-back-word
        meow-block
        meow-bounds-of-thing
        meow-change
        meow-delete
        meow-find
        meow-inner-of-thing
        meow-insert
        meow-insert-exit
        meow-kill
        meow-left
        meow-mark-symbol
        meow-mark-word
        meow-next
        meow-next-symbol
        meow-next-word
        meow-prev
        meow-reverse
        meow-right
        meow-till
        upcase-dwim
        ))

(setq mc/cmds-to-run-once
      '(
        meow-undo
        swb/meow-find-mc
        swb/meow-till-mc
        switch-to-buffer
        text-scale-adjust
        ))
