set -g base-index 1
setw -g pane-base-index 1

set -sg terminal-overrides ",*:RGB"

set -g mode-keys vi

unbind C-b
set -g prefix `
bind-key ` send-prefix

set -g status-position top
set -g status-bg black
set -g status-fg white

bind R source-file ~/.tmux.conf

unbind \"
unbind \%
bind b split-window -h
bind v split-window -v

unbind Left
unbind Down
unbind Up
unbind Right
bind h select-pane -L
bind j select-pane -U
bind k select-pane -D
bind l select-pane -R

unbind C-Left
unbind C-Down
unbind C-Up
unbind C-Right
unbind M-Left
unbind M-Down
unbind M-Up
unbind M-Right
unbind S-Left
unbind S-Down
unbind S-Up
unbind S-Right
bind -r C-h resize-pane -L 1
bind -r C-j resize-pane -D 1
bind -r C-k resize-pane -U 1
bind -r C-l resize-pane -R 1

bind-key -Tcopy-mode-vi a \
    send-keys -X copy-line \; \
    send-keys -X cancel \; \
    run "wl-paste | tr -d '\n' | tmux load-buffer - && tmux paste-buffer" \; \
    send-keys -t '0' C-a
