[ids]

*

[global]

overload-tap-timeout = 200

[main]

esc = toggle(gaming)
capslock = overload(control, esc)

shift = oneshot(shift)
meta = oneshot(meta)
control = oneshot(control)
leftalt = oneshot(alt)
rightalt = oneshot(altgr)

[gaming]

esc = esc
control = toggle(gaming)

shift = layer(shift)
meta = layer(meta)
capslock = layer(control)
leftalt = layer(alt)
rightalt = layer(altgr)
