[ids]

*

[global]

overload_tap_timeout = 200

[main]

esc = toggle(gaming)
capslock = overload(control, esc)

[gaming]

esc = esc
control = toggle(gaming)

shift = layer(shift)
meta = layer(meta)
capslock = layer(control)
leftalt = layer(alt)
rightalt = layer(altgr)
