#!/bin/bash
set -e

session="default"

if [[ $(kak -l | rg "^$session$") = "" ]]; then
    kak -d -s $session &
fi

open_kak() {
    file=$1
    line=$2
    col=$3

    args="-c $session"

    if [[ $line = "" ]]; then
        kak $args $file
    elif [[ $col = "" ]]; then
        kak $args $file +$line
    else
        kak $args $file +$line:$col
    fi
}

input=$1
if [[ $input = "" ]]; then read input; fi

open_kak $(echo "$input" | awk -F: '{print $1, $2, $3}')
