#!/bin/bash

open_in_editor() {
    file=$1
    line=$2
    col=$(($3 - 1))
    if [[ $line = "" ]]
    then
        kak $file
        exit 0
    elif [[ $(($col < 1)) = "1" ]]
    then
        kak $1 +$2
        exit 0
    fi
    kak $file +$line -e "exec $col\l"
}

input=$1

if [[ $input = "" ]]
then
    read input
fi

if [[ $input = "" ]]
then
    echo "no input provided"
    exit 1
fi
open_in_editor $(echo "$input" | awk -F: '{print $1, $2, $3}')
